### ISSUE TITLE
[Feature]: Add more inline ignore options

### ISSUE THREAD

**Issue by Cielquan** [rstcheck/rstcheck#103]
### To Dos

- [X] I have checked the [issues](https://github.com/myint/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

Currently only ignore-language is supported as inline comment. I want to check if support for the other ignore-* settings can be realized as inline comments as well.

### Operating System

Other

### Python Version

-

### rstcheck Version

5.0.0

**Comment by Cielquan** [comment]
This issue is currently still in triage, because I am at the moment not sure which ignore_* settings can really be implemented as inline comments, but I hope to find a way to implement all that make sense.

This can possibly be a solution to #120.

**Comment by Cielquan** [comment]
I will try to add support for:
- ignore_directives
- ignore_roles
- ignore_substitutions

**Comment by Cielquan** [comment]
I will also try to implement `ignore-next-code-block`.

**Comment by Cielquan** [comment]
> I will try to add support for:
> 
> * ignore_directives
> * ignore_roles
> * ignore_substitutions

I found a way to implement the mentioned configs inline.

**Comment by DanielNoord** [comment]
@Cielquan Yes this works! Thanks!

I did find another issue, for which I will open another issue 👍

**Comment by Cielquan** [comment]
That's great to hear.

This feature will presumably be released with v6.0 after all. Because I want to investigate your bug and another bug I detected yesterday and when the release date moves to the future anyways, why not also release this feature then.
