### ISSUE TITLE
[Question]: how can I avoid my nice markdown tables in a README.rst file to trigger (ERROR/3) (bash) syntax error near unexpected token `|'

### ISSUE THREAD

**Issue by TheBigBear** [rstcheck/rstcheck#134]
### To Dos

- [X] I already searched with my favorite search engine "How to do X with rstcheck".
- [X] I already read and followed the README and didn't find an answer.
- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

I have tried adding very nice looking markdown tables that use pipe symbols and other un-expected character sequences and it of course triggers rstcheck errors ```(ERROR/3) (bash) syntax error near unexpected token `|'``` 

What is the best way to exclude such a markdown table stanza from being flagged in the pre commit hook? 

I have no control over the git repo I am submitting my "pretty" PRs to. But the poor maintainers  trying to merge my PRs do not like my PRs. 

What can I do? 

Sample lines submitted to a README.rst that triggers this is: 

```markdown
# Setup venv
| linux & macos                          | windows *                              |
|:--------------------------------------:|:--------------------------------------:|
| python3 -m venv .venv --prompt idemenv | python3 -m venv .venv --prompt idemenv |
| source .venv/bin/activate              | . .venv\Scripts\activate               |
| pip install -e .                       | pip install -e .                       |

* Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":
https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

### Operating System

Linux

### Python Version

3.8.12

### rstcheck Version

v5.0.0

EDIT1 by @Cielquan: Put source in source markdown

**Comment by TheBigBear** [comment]
One such PR can be found at https://github.com/eitrtechnologies/idemenv/pull/6

**Comment by polyzen** [comment]
You can't use Markdown in reStructuredText. See here how tables work in rST:
https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#tables

**Comment by Cielquan** [comment]
With @polyzen 's comment I guess this issue is resolved. If you have further questions or problems feel free to reopen the issue.
