### ISSUE TITLE
[Feature]: Upgrade docutils to <0.2

### ISSUE THREAD

**Issue by vepain** [rstcheck/rstcheck#147]
### To Dos

- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

There is a dependencies conflict between package `m2r2==0.3.3` and `rstcheck==6.1.0`.
First one need `docutils>=0.19`, second one need `docutils<0.19`

### Operating System

Linux

### Python Version

Python 3.9.5

### rstcheck Version

rstcheck 6.1.0

**Comment by Cielquan** [comment]
I will try to ix this within this week.

I will need to prior fix the failing CI in #145 caused by the update in the PR. But after that I will take a look at dependency updates, inculding this.

**Comment by Cielquan** [comment]
`docutils` will be removed as a direct dependency in #149.

rstcheck-core took this dependency over, therefore the followup issue: https://github.com/rstcheck/rstcheck-core/issues/20

**Comment by Cielquan** [comment]
rstcheck-core v1.0.3 is released and has the more open version constraint.
