### ISSUE TITLE
[Feature]: Add support for YAML in Code Blocks

### ISSUE THREAD

**Issue by rbjorklin** [rstcheck/rstcheck#219]
### To Dos

- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

I would like to see support for YAML in code blocks.

### Operating System

Linux

### Python Version

3.12.2

### rstcheck Version

3.3.1

**Comment by Cielquan** [comment]
YAML support was added with rstcheck-core v1.2.0 last year

https://github.com/rstcheck/rstcheck-core/blob/main/CHANGELOG.md
