### ISSUE TITLE
the typer[all] dep is causing issues when using typer > 0.12.0 

### ISSUE THREAD

**Issue by ryanlerch** [rstcheck/rstcheck#223]
### To Dos

- [X] I already searched with my favorite search engine "How to do X with rstcheck".
- [X] I already read and followed the README and didn't find an answer.
- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

Typer has changed they way it is packaged in version 0.12.0 and the `typer[all]` dep being used in the rstcheck pyproject.toml is no longer working, AFAICT, it is now `typer[standard]`

### Operating System

Other

### Python Version

3

### rstcheck Version

6.2.1

**Comment by Cielquan** [comment]
Sorry for the long silence. Do you want to make a PR to fix this?

**Comment by Cielquan** [comment]
Release in 6.2.2
