### ISSUE TITLE
Please add test files to the release archive

### ISSUE THREAD

**Issue by zyga** [rstcheck/rstcheck#75]
Hello

I'm working on a Debian package for rstcheck and I would like to run the test suite at build time. Could you please ship the two test files in the code archive using the `MANIFEST.in` system?

**Comment by Cielquan** [comment]
I updated the build process entirely.

The `test_rstcheck.py` and `test.bash` files are added to the tarball but not the wheel.

**Comment by Cielquan** [comment]
I changed a lot with the testing stuff.

Tests are all now included in sdist including the examples needed for the system tests to run.
The system tests were rewritten from the test.bash script to pytest tests like the unit tests too.
