### ISSUE TITLE
Explicit hyperlink target should silence "duplicate implicit target name" message

### ISSUE THREAD

**Issue by inventhouse** [rstcheck/rstcheck#76]
If there are sections with the same title, a `Duplicate implicit target name` message is generated; however the [documentation for explicit targets](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#explicit-hyperlink-targets), while not addressing this specific case, describe adding explicit hyperlink targets by placing them just before the block to be targeted.  This seems (to me) to imply that [this StackOverflow answer](https://stackoverflow.com/a/39720161/12288422) _should_ work to silence this warning, but it does not.

**Comment by phlax** [comment]
+1 im guessing the workarounds are either to raise level to warn (as suggested in SO discussion - pretty undesirable tbh) or to filter out these messages

it would be great if this was fixed

**Comment by Cielquan** [comment]
I can reproduce this issue.

Are you willing to tackle it?

**Comment by Cielquan** [comment]
I looked into the matter and this is an issue with docutils and not rstcheck. rstcheck simply passes the info message on.

If you open an issue over at https://sourceforge.net/p/docutils/_list/tickets please link it here, so we can follow the progress.
